### ISSUE TITLE
npm ERR! react@"^18.2.0" 

### ISSUE THREAD

**Issue by maifumei** [jeslage/react-pick-color#58] opened 2023-08-11 08:25 UTC
npm ERR! react@"^18.2.0" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-pick-color@1.0.4

Please upgrade your package to react 18 version.

**Comment by jeslage** [comment] 2023-08-13 08:13
Duplicate of #57

**Comment by jeslage** [comment] 2023-08-13 08:13
@maifumei i will look into this. I will close this ticket and will resolve it in the duplicate.

**Closed by jeslage** 2023-08-13 08:13 UTC

**Comment by jeslage** [comment] 2023-08-13 18:16
Fixed it with version 2.0.0.
